//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMO.SDNI.RECURSOS {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Equinova {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Equinova() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPMO.SDNI.RECURSOS.Equinova", typeof(Equinova).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SECTOR.
        /// </summary>
        public static string CLI01 {
            get {
                return ResourceManager.GetString("CLI01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE CLIENTE.
        /// </summary>
        public static string CLI02 {
            get {
                return ResourceManager.GetString("CLI02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TELÉFONO.
        /// </summary>
        public static string CLI03 {
            get {
                return ResourceManager.GetString("CLI03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FT.
        /// </summary>
        public static string EQ01 {
            get {
                return ResourceManager.GetString("EQ01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACCESORIO.
        /// </summary>
        public static string RE00 {
            get {
                return ResourceManager.GetString("RE00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SERIE UNIDAD.
        /// </summary>
        public static string RE01 {
            get {
                return ResourceManager.GetString("RE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLAVE ACTIVO ORACLE.
        /// </summary>
        public static string RE02 {
            get {
                return ResourceManager.GetString("RE02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID LIDER.
        /// </summary>
        public static string RE03 {
            get {
                return ResourceManager.GetString("RE03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eCODE.
        /// </summary>
        public static string RE04 {
            get {
                return ResourceManager.GetString("RE04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO UNIDAD.
        /// </summary>
        public static string RE05 {
            get {
                return ResourceManager.GetString("RE05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MARCA.
        /// </summary>
        public static string RE06 {
            get {
                return ResourceManager.GetString("RE06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MODELO.
        /// </summary>
        public static string RE07 {
            get {
                return ResourceManager.GetString("RE07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AÑO.
        /// </summary>
        public static string RE08 {
            get {
                return ResourceManager.GetString("RE08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA COMPRA.
        /// </summary>
        public static string RE09 {
            get {
                return ResourceManager.GetString("RE09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # FACTURA.
        /// </summary>
        public static string RE10 {
            get {
                return ResourceManager.GetString("RE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FABRICANTE.
        /// </summary>
        public static string RE11 {
            get {
                return ResourceManager.GetString("RE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COSTO ADQUISICIÓN.
        /// </summary>
        public static string RE12 {
            get {
                return ResourceManager.GetString("RE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA INICIO DE DEPRECIACIÓN.
        /// </summary>
        public static string RE13 {
            get {
                return ResourceManager.GetString("RE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FECHA IDEAL DE DESFLOTE.
        /// </summary>
        public static string RE14 {
            get {
                return ResourceManager.GetString("RE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TASA DEPRECIACIÓN.
        /// </summary>
        public static string RE15 {
            get {
                return ResourceManager.GetString("RE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VIDA ÚTIL (AÑOS).
        /// </summary>
        public static string RE16 {
            get {
                return ResourceManager.GetString("RE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PORCENTAJE VALOR RESIDUAL.
        /// </summary>
        public static string RE17 {
            get {
                return ResourceManager.GetString("RE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VALOR RESIDUAL.
        /// </summary>
        public static string RE18 {
            get {
                return ResourceManager.GetString("RE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALDO POR DEPRECIAR (VALOR EN LIBROS).
        /// </summary>
        public static string RE19 {
            get {
                return ResourceManager.GetString("RE19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOTORIZACIÓN.
        /// </summary>
        public static string RE20 {
            get {
                return ResourceManager.GetString("RE20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APLICACIÓN.
        /// </summary>
        public static string RE21 {
            get {
                return ResourceManager.GetString("RE21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRÓXIMO SERVICIO.
        /// </summary>
        public static string RE22 {
            get {
                return ResourceManager.GetString("RE22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRÓXIMO SERVICIO (HRS).
        /// </summary>
        public static string RE23 {
            get {
                return ResourceManager.GetString("RE23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO APLICA.
        /// </summary>
        public static string RE24 {
            get {
                return ResourceManager.GetString("RE24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HORÓMETRO INICIAL.
        /// </summary>
        public static string RE25 {
            get {
                return ResourceManager.GetString("RE25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAPACIDAD DE TANQUE.
        /// </summary>
        public static string RE26 {
            get {
                return ResourceManager.GetString("RE26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE27 {
            get {
                return ResourceManager.GetString("RE27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE28 {
            get {
                return ResourceManager.GetString("RE28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE29 {
            get {
                return ResourceManager.GetString("RE29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE30 {
            get {
                return ResourceManager.GetString("RE30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE31 {
            get {
                return ResourceManager.GetString("RE31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE32 {
            get {
                return ResourceManager.GetString("RE32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        public static string RE33 {
            get {
                return ResourceManager.GetString("RE33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIPO DE RENTA.
        /// </summary>
        public static string RE34 {
            get {
                return ResourceManager.GetString("RE34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TENENCIA.
        /// </summary>
        public static string RE35 {
            get {
                return ResourceManager.GetString("RE35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLACA ESTATAL.
        /// </summary>
        public static string RE36 {
            get {
                return ResourceManager.GetString("RE36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO APLICA.
        /// </summary>
        public static string RE37 {
            get {
                return ResourceManager.GetString("RE37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO APLICA.
        /// </summary>
        public static string RE38 {
            get {
                return ResourceManager.GetString("RE38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO APLICA.
        /// </summary>
        public static string RE39 {
            get {
                return ResourceManager.GetString("RE39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NO APLICA.
        /// </summary>
        public static string RE40 {
            get {
                return ResourceManager.GetString("RE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GPS.
        /// </summary>
        public static string RE41 {
            get {
                return ResourceManager.GetString("RE41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILTRO AK.
        /// </summary>
        public static string RE42 {
            get {
                return ResourceManager.GetString("RE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a # PEDIMENTO.
        /// </summary>
        public static string RE43 {
            get {
                return ResourceManager.GetString("RE43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PROVEEDOR.
        /// </summary>
        public static string RE44 {
            get {
                return ResourceManager.GetString("RE44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ../Contenido/Imagenes/MREBienv.jpg.
        /// </summary>
        public static string RE45 {
            get {
                return ResourceManager.GetString("RE45", resourceCulture);
            }
        }
    }
}
