//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMO.SDNI.RECURSOS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idealease {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idealease() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPMO.SDNI.RECURSOS.Idealease", typeof(Idealease).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIAS USO UNIDAD(MES).
        /// </summary>
        public static string CLI01 {
            get {
                return ResourceManager.GetString("CLI01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO CUENTA.
        /// </summary>
        public static string CLI02 {
            get {
                return ResourceManager.GetString("CLI02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORAS USO UNIDAD(DIA).
        /// </summary>
        public static string CLI03 {
            get {
                return ResourceManager.GetString("CLI03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PBC.
        /// </summary>
        public static string EQ01 {
            get {
                return ResourceManager.GetString("EQ01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string RE00 {
            get {
                return ResourceManager.GetString("RE00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string RE01 {
            get {
                return ResourceManager.GetString("RE01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLAVE ACTIVO ORACLE.
        /// </summary>
        public static string RE02 {
            get {
                return ResourceManager.GetString("RE02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID LIDER.
        /// </summary>
        public static string RE03 {
            get {
                return ResourceManager.GetString("RE03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # ECONÓMICO.
        /// </summary>
        public static string RE04 {
            get {
                return ResourceManager.GetString("RE04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPO UNIDAD.
        /// </summary>
        public static string RE05 {
            get {
                return ResourceManager.GetString("RE05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCA.
        /// </summary>
        public static string RE06 {
            get {
                return ResourceManager.GetString("RE06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODELO.
        /// </summary>
        public static string RE07 {
            get {
                return ResourceManager.GetString("RE07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AÑO.
        /// </summary>
        public static string RE08 {
            get {
                return ResourceManager.GetString("RE08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FECHA COMPRA.
        /// </summary>
        public static string RE09 {
            get {
                return ResourceManager.GetString("RE09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # FACTURA.
        /// </summary>
        public static string RE10 {
            get {
                return ResourceManager.GetString("RE10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FABRICANTE.
        /// </summary>
        public static string RE11 {
            get {
                return ResourceManager.GetString("RE11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTO FACTURA.
        /// </summary>
        public static string RE12 {
            get {
                return ResourceManager.GetString("RE12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE13 {
            get {
                return ResourceManager.GetString("RE13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE14 {
            get {
                return ResourceManager.GetString("RE14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE15 {
            get {
                return ResourceManager.GetString("RE15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE16 {
            get {
                return ResourceManager.GetString("RE16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE17 {
            get {
                return ResourceManager.GetString("RE17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE18 {
            get {
                return ResourceManager.GetString("RE18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE19 {
            get {
                return ResourceManager.GetString("RE19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTORIZACIÓN.
        /// </summary>
        public static string RE20 {
            get {
                return ResourceManager.GetString("RE20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APLICACIÓN.
        /// </summary>
        public static string RE21 {
            get {
                return ResourceManager.GetString("RE21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRÓXIMO SERVICIO.
        /// </summary>
        public static string RE22 {
            get {
                return ResourceManager.GetString("RE22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRÓXIMO SERVICIO (KM).
        /// </summary>
        public static string RE23 {
            get {
                return ResourceManager.GetString("RE23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAL (KM).
        /// </summary>
        public static string RE24 {
            get {
                return ResourceManager.GetString("RE24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAL (HRS).
        /// </summary>
        public static string RE25 {
            get {
                return ResourceManager.GetString("RE25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMBUSTIBLE TOTAL.
        /// </summary>
        public static string RE26 {
            get {
                return ResourceManager.GetString("RE26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE27 {
            get {
                return ResourceManager.GetString("RE27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE28 {
            get {
                return ResourceManager.GetString("RE28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE29 {
            get {
                return ResourceManager.GetString("RE29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE30 {
            get {
                return ResourceManager.GetString("RE30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE31 {
            get {
                return ResourceManager.GetString("RE31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE32 {
            get {
                return ResourceManager.GetString("RE32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RE33 {
            get {
                return ResourceManager.GetString("RE33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREA/DEPARTAMENTO.
        /// </summary>
        public static string RE34 {
            get {
                return ResourceManager.GetString("RE34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TENENCIA.
        /// </summary>
        public static string RE35 {
            get {
                return ResourceManager.GetString("RE35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACA ESTATAL.
        /// </summary>
        public static string RE36 {
            get {
                return ResourceManager.GetString("RE36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEGURO.
        /// </summary>
        public static string RE37 {
            get {
                return ResourceManager.GetString("RE37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLACA FEDERAL.
        /// </summary>
        public static string RE38 {
            get {
                return ResourceManager.GetString("RE38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICACIÓN AMBIENTAL.
        /// </summary>
        public static string RE39 {
            get {
                return ResourceManager.GetString("RE39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFICACIÓN FÍSICO MECÁNICA.
        /// </summary>
        public static string RE40 {
            get {
                return ResourceManager.GetString("RE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        public static string RE41 {
            get {
                return ResourceManager.GetString("RE41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTRO AK.
        /// </summary>
        public static string RE42 {
            get {
                return ResourceManager.GetString("RE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO APLICA.
        /// </summary>
        public static string RE43 {
            get {
                return ResourceManager.GetString("RE43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPIETARIO.
        /// </summary>
        public static string RE44 {
            get {
                return ResourceManager.GetString("RE44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../Contenido/Imagenes/WorkInProgress.png.
        /// </summary>
        public static string RE45 {
            get {
                return ResourceManager.GetString("RE45", resourceCulture);
            }
        }
    }
}
