//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPMO.SDNI.Contratos.PSL.UI {
    
    
    public partial class RegistrarEntregaPSLUI {
        
        /// <summary>
        /// lblEncabezadoLeyenda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEncabezadoLeyenda;
        
        /// <summary>
        /// hlConsultar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlConsultar;
        
        /// <summary>
        /// btnGuardar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        
        /// <summary>
        /// btnCancelar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        /// <summary>
        /// hdnContratoID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnContratoID;
        
        /// <summary>
        /// hdnLineaContratoID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnLineaContratoID;
        
        /// <summary>
        /// hdnFechaContrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnFechaContrato;
        
        /// <summary>
        /// hdnHoraContrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnHoraContrato;
        
        /// <summary>
        /// hdnEstatusContratoID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnEstatusContratoID;
        
        /// <summary>
        /// hdnTipoCheckList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnTipoCheckList;
        
        /// <summary>
        /// hdnTipoListadoVerificacionPSL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnTipoListadoVerificacionPSL;
        
        /// <summary>
        /// hdnTipoContrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnTipoContrato;
        
        /// <summary>
        /// hdnArea control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnArea;
        
        /// <summary>
        /// txtNumeroContrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroContrato;
        
        /// <summary>
        /// txtNombreCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNombreCliente;
        
        /// <summary>
        /// txtNumeroLicencia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroLicencia;
        
        /// <summary>
        /// hdnUnidadID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnUnidadID;
        
        /// <summary>
        /// hdnEquipoID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnEquipoID;
        
        /// <summary>
        /// hdnCapacidadTanque control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnCapacidadTanque;
        
        /// <summary>
        /// txtNumeroEconomico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroEconomico;
        
        /// <summary>
        /// txtNumeroSerie control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNumeroSerie;
        
        /// <summary>
        /// txtPlacasEstatales control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtPlacasEstatales;
        
        /// <summary>
        /// ucucEquiposAliadosUnidadUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Flota.UI.ucEquiposAliadosUnidadUI ucucEquiposAliadosUnidadUI;
        
        /// <summary>
        /// txtFechaSalida control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFechaSalida;
        
        /// <summary>
        /// txtNombreUsuarioEntrega control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNombreUsuarioEntrega;
        
        /// <summary>
        /// txtCombustibleSalida control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCombustibleSalida;
        
        /// <summary>
        /// txtHoraSalida control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtHoraSalida;
        
        /// <summary>
        /// txtHorometro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtHorometro;
        
        /// <summary>
        /// txtTanqueCobustible control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTanqueCobustible;
        
        /// <summary>
        /// hdnHorometroAnterior control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnHorometroAnterior;
        
        /// <summary>
        /// mvPuntosVerificacion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.MultiView mvPuntosVerificacion;
        
        /// <summary>
        /// vwPuntosVerificacionCompresoresPortatiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionCompresoresPortatiles;
        
        /// <summary>
        /// ucPuntosVerificacionCompresoresPortatilesPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionCompresoresPortatilesPSLUI ucPuntosVerificacionCompresoresPortatilesPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionMontaCarga control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionMontaCarga;
        
        /// <summary>
        /// ucPuntosVerificacionMontaCargaPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionMontaCargaPSLUI ucPuntosVerificacionMontaCargaPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionMotoNiveladora control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionMotoNiveladora;
        
        /// <summary>
        /// ucPuntosVerificacionMotoNiveladoraPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionMotoNiveladoraPSLUI ucPuntosVerificacionMotoNiveladoraPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionMiniCargador control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionMiniCargador;
        
        /// <summary>
        /// ucPuntosVerificacionMiniCargadorPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionMiniCargadorPSLUI ucPuntosVerificacionMiniCargadorPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionMartilloHidraulico control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionMartilloHidraulico;
        
        /// <summary>
        /// ucPuntosVerificacionMartilloHidraulicoPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionMartilloHidraulicoPSLUI ucPuntosVerificacionMartilloHidraulicoPSLUI;
        
        /// <summary>
        /// mvPuntosVerificacionEntrega control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View mvPuntosVerificacionEntrega;
        
        /// <summary>
        /// ucPuntosVerificacionEntregaRecepcionPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionEntregaRecepcionPSLUI ucPuntosVerificacionEntregaRecepcionPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionExcavadora control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionExcavadora;
        
        /// <summary>
        /// ucPuntosVerificacionExcavadoraPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionExcavadoraPSLUI ucPuntosVerificacionExcavadoraPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionSubArrendado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionSubArrendado;
        
        /// <summary>
        /// ucPuntosVerificacionSubArrendadoPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionSubArrendadoPSLUI ucPuntosVerificacionSubArrendadoPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionTorresLuz control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionTorresLuz;
        
        /// <summary>
        /// ucPuntosVerificacionTorresLuzPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionTorresLuzPSLUI ucPuntosVerificacionTorresLuzPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionPlataformaTijeras control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionPlataformaTijeras;
        
        /// <summary>
        /// ucPuntosVerificacionPlataformaTijerasPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionPlataformaTijerasPSLUI ucPuntosVerificacionPlataformaTijerasPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionRetroExcavadora control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionRetroExcavadora;
        
        /// <summary>
        /// ucPuntosVerificacionRetroExcavadoraPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionRetroExcavadoraPSLUI ucPuntosVerificacionRetroExcavadoraPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionVibroCompactador control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionVibroCompactador;
        
        /// <summary>
        /// ucPuntosVerificacionVibroCompactadorPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionVibroCompactadorPSLUI ucPuntosVerificacionVibroCompactadorPSLUI;
        
        /// <summary>
        /// vwPuntosVerificacionPistolaNeumatica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.View vwPuntosVerificacionPistolaNeumatica;
        
        /// <summary>
        /// ucPuntosVerificacionPistolaNeumaticaPSLUI control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Contratos.PSL.UI.ucPuntosVerificacionPistolaNeumaticaPSLUI ucPuntosVerificacionPistolaNeumaticaPSLUI;
        
        /// <summary>
        /// ucCatalogoDocumentos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BPMO.SDNI.Comun.UI.ucCatalogoDocumentosUI ucCatalogoDocumentos;
        
        /// <summary>
        /// txtObservaciones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
    }
}
